### ISSUE TITLE
[Bug] Placeholder is duplicated

### ISSUE THREAD

**Issue by raducanb** [qiwi/FormattableTextView#6]
Firstly congrats Qiwi team for an impressive library 👏 .

Running the Example project provided, I modified the first format to be `"DD/MM/YYYY"`. Also, I added the following `formatSymbols`:

```swift
tv.formatSymbols = ["M": CharacterSet.decimalDigits, "D": CharacterSet.decimalDigits, "Y": CharacterSet.decimalDigits]
```

And the following `maskAppearance`:

```swift
tv.maskAppearance = .whole(placeholders: ["D": "D", "M": "M", "Y": "Y"])
```

This configuration formats the input as expected (so I can enter for example `12/05/2000`), but the problem is that **the placeholder appears two times**. This happens both with UITextField & UITextView options.

Do you have any suggestions in what section of the code I could look in order to fix it? Or am I doing something wrong with the configuration?

<img width="200px" src="https://user-images.githubusercontent.com/4189954/120279295-8cfa9180-c2b6-11eb-9a50-b2083493c74c.png" />

**Comment by live-sound** [comment]
Thank you for your report! The bug has been fixed.

**Comment by raducanb** [comment]
@zlib thank you! Do you have plans for making a new release that includes this bugfix?

**Comment by live-sound** [comment]
New release is ready.
