### ISSUE TITLE
[Bug] Layout problem when using default UIFont system

### ISSUE THREAD

**Issue by raducanb** [qiwi/FormattableTextView#7]
In the example project, if I change the `wholeMaskAttributes` & `wholeInputAttributes` to use `UIFont.systemFont`, the layout is no longer correct because the placeholder has an offset compared to the input text.

```swift
let wholeMaskAttributes = [NSAttributedString.Key.font: UIFont.systemFont(ofSize: 16), NSAttributedString.Key.foregroundColor: UIColor.lightGray]
let wholeInputAttributes = [NSAttributedString.Key.font: UIFont.systemFont(ofSize: 16)]
```

It's a limitation of the library, it works only with fonts that have a specific character size?

Result:

https://user-images.githubusercontent.com/4189954/120436395-29886680-c37f-11eb-9158-2357fe1cee9f.mov
<img width="300" alt="Capture d’écran 2021-06-02 à 08 45 08" src="https://user-images.githubusercontent.com/4189954/120436437-360cbf00-c37f-11eb-80e7-234b1a3a4397.png">

**Comment by live-sound** [comment]
The "whole" style requires monospaced font, it is written in README.
